source 'https://rubygems.org'

gem 'benchmark'
gem 'cookstyle'
gem 'csv'
gem 'highline'
gem 'inspec-bin'
gem 'kitchen-ansible'
gem 'kitchen-docker'
gem 'kitchen-dokken'
gem 'kitchen-ec2'
gem 'kitchen-inspec'
gem 'kitchen-sync'
gem 'kitchen-vagrant'
gem 'parser', '3.3.0.5'
gem 'pry-byebug'
gem 'rake'
gem 'rubocop'
gem 'rubocop-rake'
gem 'syslog'
gem 'test-kitchen'
gem 'train-awsssm'

source 'https://rubygems.cinc.sh/' do
  gem 'chef-config'
  gem 'chef-utils'
  gem 'cinc-auditor-bin'
  gem 'inspec', '>= 6.6.0'
  gem 'inspec-core'
end
