platforms:
- name: rhel-9

driver:
  name: ec2
  image_search:
    owner-id: "174003430611"
    name: spel-minimal-rhel-9*
  #subnet_id: "<%= ENV['SAF_PIPELINE_SUBNET'] %>"
  #security_group_ids:
  #- "<%= ENV['SAF_PIPELINE_SG'] %>"
  metadata_options:
    http_tokens: required
    http_put_response_hop_limit: 1
    instance_metadata_tags: enabled
  instance_type: t2.small
  associate_public_ip: true
  interface: public
  skip_cost_warning: true
  privileged: true
  instance_initiated_shutdown_behavior: terminate
  # aws_ssh_key_type: ed25519
  # aws_ssh_key_id: 'ed-key'

provisioner:
  name: ansible_playbook
  hosts: all
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_binary_path: /usr/local/bin
  require_pip3: true
  ansible_verbose: true
  roles_path: spec/ansible/roles
  galaxy_ignore_certs: true
  requirements_path: spec/ansible/roles/requirements.yml
  requirements_collection_path: spec/ansible/roles/requirements.yml
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>

suites:
- name: vanilla
  provisioner:
    playbook: spec/ansible/roles/ansible-role-rhel-vanilla.yml
  driver:
    tags:
      Name: Vanilla-<%= ENV['USER'] %>
      CreatedBy: test-kitchen

- name: hardened
  provisioner:
    playbook: spec/ansible/roles/ansible-role-rhel-hardened.yml
  driver:
    tags:
      Name: Hardened-<%= ENV['USER'] %>
      CreatedBy: test-kitchen

lifecycle:
  pre_converge:
  - remote: |
      # echo "+++ Refreshing DNF package cache +++"
      # sudo dnf -y clean all
      echo ""
      echo "+++ Updating DNF Packages +++"
      sudo dnf -y update --nogpgcheck --nobest
      echo ""
      echo "+++ Installing needed packages for workflow and utility +++\n\n"
      sudo dnf -y install --nogpgcheck bc bind-utils redhat-lsb-core vim git wget gcc openssl-devel libffi-devel bzip2-devel
      echo ""
      # echo "+++ Installing Python 3.9 and Ansible +++\n\n"
      # export PATH=/usr/local/bin:$PATH
      # sudo dnf -y install python3-pip
      # sudo python3 -m pip install ansible jmespath
      # echo ""
      echo "+++ Updating the maintuser to keep sudo working after hardening phase +++\n\n"
      sudo chage -d $(( $( date +%s ) / 86400 )) maintuser
      echo ""
      echo "+++ updating maintuser sudo config for hardening phase +++\n\n"
      sudo chmod 600 /etc/sudoers && sudo sed -i'' "/maintuser/d" /etc/sudoers && sudo chmod 400 /etc/sudoers
      sudo dnf -y install git
      echo "+++ add cinc-auditor for local shell +++\n\n"
      curl -L https://omnitruck.cinc.sh/install.sh | sudo bash -s -- -P cinc-auditor

transport:
  name: ssh
  #https://github.com/neillturner/kitchen-ansible/issues/295
  max_ssh_sessions: 2
  username: maintuser
  # ssh_key: ~/.ssh/ed-key.pem
